// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_Nomina;

#nullable disable

namespace PruebaNomina.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221219054039_Creando_Tablas")]
    partial class CreandoTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba_Nomina.Entities.Estado_civil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Estados_Civiles");
                });

            modelBuilder.Entity("Prueba_Nomina.Entities.Movimiento_pension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha_final")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<float>("Importe")
                        .HasColumnType("real");

                    b.Property<int>("MovimientosId")
                        .HasColumnType("int");

                    b.Property<int>("PensionadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MovimientosId");

                    b.HasIndex("PensionadoId");

                    b.ToTable("Movimientos_Pensionados");
                });

            modelBuilder.Entity("Prueba_Nomina.Entities.Movimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Movimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Prueba_Nomina.Entities.Pensionado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Clave_pension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado_civilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("No_activo")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("No_afiliado")
                        .HasColumnType("int");

                    b.Property<int>("No_pension")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.Property<bool>("Status_pago")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo_PensionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado_civilId");

                    b.HasIndex("Tipo_PensionId");

                    b.ToTable("Pensionados");
                });

            modelBuilder.Entity("Prueba_Nomina.Entities.Tipo_Pension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Pensiones");
                });

            modelBuilder.Entity("Prueba_Nomina.Entities.Movimiento_pension", b =>
                {
                    b.HasOne("Prueba_Nomina.Entities.Movimientos", "movimientos")
                        .WithMany()
                        .HasForeignKey("MovimientosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prueba_Nomina.Entities.Pensionado", "pensionado")
                        .WithMany()
                        .HasForeignKey("PensionadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movimientos");

                    b.Navigation("pensionado");
                });

            modelBuilder.Entity("Prueba_Nomina.Entities.Pensionado", b =>
                {
                    b.HasOne("Prueba_Nomina.Entities.Estado_civil", "estado_Civil")
                        .WithMany()
                        .HasForeignKey("Estado_civilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prueba_Nomina.Entities.Tipo_Pension", "tipo_Pension")
                        .WithMany()
                        .HasForeignKey("Tipo_PensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estado_Civil");

                    b.Navigation("tipo_Pension");
                });
#pragma warning restore 612, 618
        }
    }
}
